fixed : logo clicks redirect to homepage
idurar/idurar-erp-crm pull request #238
Opened 2023-08-03 11:20 UTC by chandra1899

issue:- #215

2023-08-04 03:54 UTC, quan-nh2 commented on server.js
> +app.set('port', 8888);
Need to load `port` from env first

2023-08-04 05:32 UTC, chandra1899 commented on server.js
> +app.set('port', 8888);
> Need to load `port` from env first

Updated .....

2023-08-08 21:02 UTC, salahlalami requested changes
@chandra1899 Thank you , please add this svg logo instead of png. , should be same siez

![idurar-crm-erp](https://github.com/idurar/idurar-erp-crm/assets/136928179/cad0a171-2152-4da9-9cc7-94e2ea07dcf3)

2023-08-09 07:39 UTC, chandra1899 commented
> @chandra1899 Thank you , please add this svg logo instead of png. , should be same siez
> 
> ![idurar-crm-erp](https://user-images.githubusercontent.com/136928179/259228469-cad0a171-2152-4da9-9cc7-94e2ea07dcf3.svg)

added 👍

2023-08-09 08:48 UTC, polymahh commented
@chandra1899 is this logo working correctly when the navigation is closed ?
@salahlalami navigation needs two files one for icon and one for text

2023-08-09 09:41 UTC, salahlalami requested changes
Thank you @polymahh  , 
@chandra1899 please use this two svg (text and icon) 
![logo-text](https://github.com/idurar/idurar-erp-crm/assets/136928179/86d34520-a877-47db-b91a-393b0e57ebd9)
![logo-icon](https://github.com/idurar/idurar-erp-crm/assets/136928179/23bc2efd-be07-4f9d-b2fe-b8335871459b)

2023-08-09 12:15 UTC, chandra1899 commented
> Thank you @polymahh , @chandra1899 please use this two svg (text and icon) ![logo-text](https://user-images.githubusercontent.com/136928179/259365936-86d34520-a877-47db-b91a-393b0e57ebd9.svg) ![logo-icon](https://user-images.githubusercontent.com/136928179/259365942-23bc2efd-be07-4f9d-b2fe-b8335871459b.svg)

pull request updated

2023-08-10 14:03 UTC, salahlalami approved these changes
Thank you @chandra1899

2023-08-10 14:04 UTC, merged