feat: Invoice from Quotation
idurar/idurar-erp-crm pull request #253
Opened 2023-08-08 20:52 UTC by lazyfuhrer

will close #242

2023-08-08 21:07 UTC, salahlalami approved these changes

2023-08-08 21:09 UTC, salahlalami requested changes
@lazyfuhrer here if you want work , you need to create new backend api to convert quote to invoice

2023-08-08 21:27 UTC, lazyfuhrer commented
> @lazyfuhrer here if you want work , you need to create new backend api to convert quote to invoice

based on the quote form status value, I'm creating invoices. Is it the way you want it ?

2023-08-11 13:51 UTC, salahlalami commented
here current PR for this issue : https://github.com/idurar/idurar-erp-crm/pull/274

2023-08-11 13:52 UTC, closed without merging