created quoteToInvoice converter api
idurar/idurar-erp-crm pull request #274
Opened 2023-08-11 12:00 UTC by Elham-EN

This change resolve #261 by creating the Quote to Invoice converter api.

2023-08-11 13:35 UTC, salahlalami commented
@Elham-EN Thanks ,
please add this method to quote route api

2023-08-11 13:36 UTC, salahlalami commented
@onfranciis please test it and try to enhance

2023-08-11 13:43 UTC, salahlalami requested changes

2023-08-11 13:43 UTC, salahlalami commented on controllers/erpControllers/quoteController.js
> +      message: 'Successfully converted quote to invoice',
return quote as result instead.

2023-08-18 12:49 UTC, onfranciis commented on controllers/erpControllers/quoteController.js
> +      return res.status(400).json({
Kindly use a status 409 to indicate the conflict error

2023-08-21 20:15 UTC, onfranciis commented
The updated pull request is now here #327

2023-08-21 20:15 UTC, closed without merging