feat: Fix invoice empty items api for create and update method
idurar/idurar-erp-crm pull request #296
Opened 2023-08-14 12:45 UTC by adeojoemmanuel

feat: Fix invoice empty items api for create and update method

2023-08-14 13:13 UTC, onfranciis approved these changes

2023-08-14 15:48 UTC, polymahh approved these changes

2023-08-14 21:16 UTC, Ando22 approved these changes

2023-08-16 10:09 UTC, salahlalami requested changes
if items = [] , return success: false,

2023-08-27 19:42 UTC, salahlalami approved these changes

2023-09-05 20:45 UTC, closed without merging