fix:fixed mobile navigation button overlap in customer page
idurar/idurar-erp-crm pull request #310
Opened 2023-08-16 19:06 UTC by ashmeetsmonga

Fixed #305 mobile navigation button overlap in customer page by adding the back button in customer panel and removing the menu button for add new customer panel

https://github.com/idurar/idurar-erp-crm/assets/56465357/e7c4ca88-98c3-4752-b2e1-0fc6958f4a72

2023-08-18 00:39 UTC, polymahh requested changes
make the button type="text"

2023-08-18 04:30 UTC, ashmeetsmonga commented
Done @polymahh

2023-08-18 09:31 UTC, polymahh approved these changes
ok thank you, when this is approved we can work on it more

2023-08-20 18:51 UTC, onfranciis approved these changes

2023-08-20 18:57 UTC, Ando22 approved these changes

2023-08-20 19:02 UTC, Fernando7181 approved these changes

2023-08-20 19:18 UTC, merged