fix #318 Capitalized table and form fields
idurar/idurar-erp-crm pull request #329
Opened 2023-08-22 05:17 UTC by Nam1001

fix #318
Now Table and Form fields are properly capitalized

Here are some screenshots

![image](https://github.com/idurar/idurar-erp-crm/assets/96697397/b0f0e6f9-db2b-417c-acfc-4a77231fc6a0)

![image](https://github.com/idurar/idurar-erp-crm/assets/96697397/8d3725c9-0bb9-4128-8eab-a0cf3d4d909b)

2023-08-22 05:18 UTC, Nam1001 commented
hey @polymahh look at this pr

2023-08-22 09:29 UTC, salahlalami requested changes
@Nam1001 pls revert tmp.variables.env file

2023-08-22 11:20 UTC, Nam1001 commented
@polymahh 
@salahlalami  
hey i have added tmp.variable.env and also my PR will close issue #210 please review it and let me know

2023-08-22 11:32 UTC, polymahh approved these changes
@Nam1001 thank you, everything seems good now

2023-08-22 14:33 UTC, Ando22 commented on frontend/src/forms/ٌRoleForm.jsx
> +        label="CodeName"
can you change this into `Code Name` instead of `CodeName`

2023-08-23 17:24 UTC, Ando22 commented on frontend/src/forms/ٌRoleForm.jsx
> +        label="CodeName"
thank you!

2023-08-23 17:25 UTC, Ando22 approved these changes

2023-08-23 18:30 UTC, Nam1001 commented
@salahlalami please review this pr

2023-08-25 12:41 UTC, adeojoemmanuel approved these changes

2023-08-27 19:47 UTC, salahlalami approved these changes
@Nam1001 Thank you

2023-08-27 19:47 UTC, merged