fixes/some standards issue/input validation
idurar/idurar-erp-crm pull request #348
Opened 2023-08-25 02:03 UTC by rkmdCodes

This PR is closing issue #341 

![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/2065e606-9216-4518-8a51-f6724b5046be)

![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/42d6e682-b784-407f-8122-34653656bffb)

![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/86096602-6cb2-4e4d-ab4c-8fb35bdda54b)

and in case any characters  
![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/67152e6a-7c6d-459e-9230-f47016259227)

![image](https://github.com/idurar/idurar-erp-crm/assets/113243168/68b2c213-20cc-4aac-838f-8a927551acc4)

2023-08-25 04:19 UTC, MattGould1 commented on frontend/src/forms/AdminForm.jsx
>              message: 'Please input your Email!',
I think the name we use for `E-mail` should be consistent. I see the label is called `E-mail` so I think this should change to `Please input your E-mail!`

2023-08-25 04:23 UTC, MattGould1 commented on frontend/src/forms/CustomerForm.jsx
> +            pattern: /^(?:[+\d()\-\s]+)$/,
Seeing as we reuse this regexp twice, it might be helpful to put it into a helper file and add a comment as to where the regexp came from.

2023-08-25 04:24 UTC, MattGould1 commented on frontend/src/forms/CustomerForm.jsx
> +            message: 'Please enter valid phone number ',
Other rules end with `!` we probably want to be consistent, and at a minimum remove the empty space as the end.

2023-08-27 17:14 UTC, polymahh requested changes
everything else is working tested

2023-08-27 17:14 UTC, polymahh commented on frontend/src/forms/EmployeeForm.jsx
> +            message: 'Please enter valid phone number ',
@rkmdCodes change this to : Please enter valid phone number!

2023-08-27 17:39 UTC, rkmdCodes commented
hi @polymahh sir
Thank you for reviewing my PR.
I have performed the requested changes.

Thanks

2023-08-27 17:53 UTC, polymahh approved these changes
tested locally

2023-08-28 00:10 UTC, salahlalami approved these changes

2023-08-29 11:49 UTC, merged