feat: provide addintional user information
idurar/idurar-erp-crm pull request #358
Opened 2023-08-27 13:59 UTC by adeojoemmanuel

2023-08-27 14:10 UTC, polymahh requested changes

2023-08-27 14:10 UTC, polymahh commented on controllers/erpControllers/authJwtController.js
> +            role: result.email,
can you extract the role?

2023-08-27 21:02 UTC, salahlalami requested changes
remove role

2023-08-27 21:02 UTC, salahlalami commented on controllers/erpControllers/authJwtController.js
> +            role: result.email,
remove role

2023-08-27 21:11 UTC, polymahh commented
@salahlalami we do need role for the profile page
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/fedb3c80-d33b-4150-9374-95c1e2548c6c)

2023-08-28 00:07 UTC, salahlalami commented
@polymahh ok, @adeojoemmanuel just keep role

2023-09-05 16:48 UTC, closed without merging