feat:moving profile compoents
idurar/idurar-erp-crm pull request #361
Opened 2023-08-28 10:11 UTC by polymahh

moving profile components to @/modules/ProfileModule/components

2023-08-28 10:45 UTC, adeojoemmanuel approved these changes

2023-08-28 11:13 UTC, salahlalami requested changes

2023-08-28 11:13 UTC, salahlalami commented on frontend/tmp.env
> +REACT_APP_BACKEND_SERVER="https://dev-server.idurarapp.com"
revert this line `REACT_APP_BACKEND_SERVER="https://your-remote-dev-server.com"`
and create new file .env and then include  `REACT_APP_BACKEND_SERVER="https://dev-server.idurarapp.com"`

2023-08-29 08:54 UTC, Ando22 approved these changes

2023-08-29 23:01 UTC, salahlalami approved these changes

2023-08-30 09:36 UTC, merged