Issues/fix login nosql injection
idurar/idurar-erp-crm pull request #419
Opened 2023-09-04 20:07 UTC by BharatPratap

Fixed  #177
Adding screenshots of testing
<img width="1011" alt="Screenshot 2023-09-05 at 1 31 48 AM" src="https://github.com/idurar/idurar-erp-crm/assets/54697708/0c6dafbb-6903-4c82-8c70-2dd4e6968836">
<img width="1006" alt="Screenshot 2023-09-05 at 1 32 03 AM" src="https://github.com/idurar/idurar-erp-crm/assets/54697708/7bfad1ea-fc0e-438c-b601-04d250652567">

<img width="1005" alt="Screenshot 2023-09-05 at 1 31 23 AM" src="https://github.com/idurar/idurar-erp-crm/assets/54697708/693dd054-630a-442a-a90d-b0076dddad80">

2023-09-04 20:15 UTC, salahlalami requested changes
@BharatPratap Thank you ,we refactor our backend , please pull again from dev branch , and add suggested solution , we will merge it

2023-09-04 20:40 UTC, BharatPratap commented
@salahlalami I have merge dev. Please check

2023-09-04 21:47 UTC, salahlalami approved these changes
Thank you @BharatPratap

2023-09-04 23:11 UTC, polymahh approved these changes

2023-09-04 23:51 UTC, merged

2023-09-05 10:32 UTC, polymahh commented
hello @BharatPratap can you commit the package.json file  i think you added joi to it

2023-09-05 11:03 UTC, BharatPratap commented
sure @polymahh

2023-09-05 11:06 UTC, BharatPratap commented
please check PR #429 for the same