feat : created a new page for advanced settings
idurar/idurar-erp-crm pull request #461
Opened 2023-09-06 11:05 UTC by polymahh

##feat: 
created a new page settings/advaced with crudModel to add new settings 

![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/3de3c023-b742-4b99-8950-52260c105615)

@salahlalami deleting a setting does not work because it is commented in the coreApi file

![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/0ca0a807-ca25-4b3b-a0a2-9998cf19694e)

2023-09-06 14:48 UTC, salahlalami requested changes
* remove coreSettings from Table & Form , by default it will be false for all user settings , and coreSettings can't be changed
* disable enabled on tabel & editForm when coreSettings is true , so user can't change it

2023-09-06 21:17 UTC, polymahh commented
now core settings cant be disabled
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/00f1b817-19f4-4af0-a73d-a50515d6c77c)

2023-09-07 20:19 UTC, salahlalami approved these changes

2023-09-08 08:21 UTC, Ando22 approved these changes

2023-09-08 10:57 UTC, merged