Feature/load default selectasync
idurar/idurar-erp-crm pull request #765
Opened 2023-11-07 09:42 UTC by johnvan7

## Description
Resolve #743 

## Checklist

- [x] I have tested these changes
- [ ] I have updated the relevant documentation
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the codebase
- [x] My changes generate no new warnings or errors
- [x] The title of my pull request is clear and descriptive

2023-11-09 21:40 UTC, salahlalami requested changes

2023-11-09 21:40 UTC, salahlalami commented on frontend/src/components/SelectAsync/index.jsx
> +  loadDefault = true,
this should be loadDefault = false, unless the user make it true

2023-11-09 21:40 UTC, salahlalami commented on frontend/src/modules/InvoiceModule/Forms/InvoiceForm.jsx
> -                  value={taxRate}
i think we need to keep this for update

2023-11-10 08:51 UTC, johnvan7 commented
Done

2023-11-10 09:20 UTC, johnvan7 commented
Also added `loadDefault={true}` in InvoiceForm, OfferForm, QuoteForm and PaymentForm because tax and paymentMode have the "isDefault" prop.

2023-11-10 09:50 UTC, merged